// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjjpfhunthmqcawiolck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqanBmaHVudGhtcWNhd2lvbGNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNjE0OTMsImV4cCI6MjA3MTkzNzQ5M30.xv8QqKIs38G3tliyponK9Andj5wb4S95mHdRNp8xyh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});